BookBundle:
    resource: "@BookBundle/Resources/config/routing.yml"
    prefix:   /

BiblioSightsMarkerBundle:
    resource: "@BiblioSightsMarkerBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
