open_layers:
    resource: "@OpenLayersBundle/Resources/config/routing.yml"
    prefix:   /openlayers

home:
  pattern: /
  defaults: { _controller: BookBundle:Default:home }

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

BookBundle:
    resource: "@BookBundle/Resources/config/routing.yml"
    prefix:   /book

MarkerBundle:
    resource: "@MarkerBundle/Resources/config/routing.yml"
    prefix:   /