security:
    firewalls:
      frontend:
        pattern: ^/*
        anonymous: ~
        form_login: 
          login_path: /user/login
          check_path: /user/login_check
          default_target_path: /
        logout:
          path: /user/logout
          target:  /
    access_control:
      - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/user/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/user/*, roles: IS_USER }
    providers:
      users:
        entity: { class: Bibliosights\UserBundle\Entity\User, property: email }
    encoders:
      Bibliosights\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }      