jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    firewalls:
      frontend:
        pattern: ^/*
        anonymous: ~
        form_login: ~
    access_control:
      - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/user/*, roles: IS_USER }
    providers:
      users:
        entity: { class: Bibliosights\UserBundle\Entity\User, property: email }
    encoders:
      Bibliosights\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }      