BiblioSightsMarkerBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MarkerBundle:Default:index }
    
BiblioSightsMarkerBundle_newMarker:
    pattern:  /newmarker
    defaults: { _controller: MarkerBundle:Default:newMarker }    
