parameters:
#    open_layers.example.class: BiblioSights\OpenLayersBundle\Example

services:
#    open_layers.example:
#        class: %open_layers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
