user_login:
    pattern:  /login
    defaults: { _controller: UserBundle:Default:login }

user_login_check:
    pattern:  /login_check

user_logout:
    pattern:  /logout
    
user_new:
    pattern: /new
    defaults: { _controller: UserBundle:Default:new }